baseURL: http://vitor.win/
languageCode: "en-us"
title: " upon the darkthrone"
relativeUrls: true
uglyURLs: true
menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 1
    - identifier: about
      name: About me.
      url: /about/
      weight: 2
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 3
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 4
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 5
params:
  abbrDateFmt: "Jan 2"
  author: "vitor"
  brandIconFile: "images/b.png"
  dateFmt: "2006-01-02"
#  customStylesheets: # Use to override theme styles, like logo size
#    - "css/custom.css"
  social:
    - name: GitHub
      url: https://github.com/vtr88
    - name: StackOverflow
      url: https://stackoverflow.com/users/1369916/vitor-hugo
    - name: Twitter
      url: https://twitter.com/bl0w
    - name: LastFM
      url: https://www.last.fm/user/bl0w
  subtitle: " bug bounty, pentest, malware/exploit, gamedev."
